[doc] Add steps how to access VisibilityOnDemand via curl
kubernetes-sigs/kueue pull request #1824
Opened 2024-03-12 12:21 UTC by xmolitann

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Docs are missing a guide on how to access VisibilityOnDemand via curl, omitting `kubectl get --raw ....`. This is needed if you want to use it programmatically.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2024-05-07 15:59 UTC, mimowo commented
/cc @PBundyra

2024-05-08 11:47 UTC, PBundyra reviewed
Thanks for the PR! Looks good, just a few nits.

2024-05-08 11:47 UTC, PBundyra commented on site/static/examples/admin/cluster-role-and-binding.yaml
> +  name: kueue-api-get
Could you please rename this to better reflect its purpose within the Visibility API?

2024-05-08 11:47 UTC, PBundyra commented on site/static/examples/admin/cluster-role-and-binding.yaml
> +  name: kueue-api-get
ditto

2024-05-08 11:47 UTC, PBundyra commented on site/static/examples/admin/cluster-role-and-binding.yaml
Could you please rename this file to better reflect its purpose within the Visibility API?

2024-05-09 11:42 UTC, PBundyra requested changes

2024-05-09 11:42 UTC, PBundyra commented on site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_on_demand.md
> +curl -X GET $APISERVER/apis/visibility.kueue.x-k8s.io/v1alpha1/clusterqueues/cluster-queue/pendingworkloads --header "Authorization: Bearer $TOKEN | jq"
```suggestion
curl -X GET $APISERVER/apis/visibility.kueue.x-k8s.io/v1alpha1/clusterqueues/cluster-queue/pendingworkloads --header "Authorization: Bearer $TOKEN" --insecure | jq
```

2024-05-09 11:42 UTC, PBundyra commented on site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_on_demand.md
> +curl -X GET $APISERVER/apis/visibility.kueue.x-k8s.io/v1alpha1/namespaces/default/localqueues/user-queue/pendingworkloads --header "Authorization: Bearer $TOKEN | jq"
```suggestion
curl -X GET $APISERVER/apis/visibility.kueue.x-k8s.io/v1alpha1/namespaces/default/localqueues/user-queue/pendingworkloads --header "Authorization: Bearer $TOKEN" --insecure | jq
```

2024-05-09 11:42 UTC, PBundyra commented on site/static/examples/admin/cluster-role-and-binding.yaml
> +  name: default
I think we're missing namespace here

2024-05-09 11:51 UTC, PBundyra commented
Due to the need of using `--insecure` flag to avoid using proxy, a user is exposed to MITM attacks which I believe is undesired. Can we find any other alternative or mitigation of this risk? 

Docs: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#without-kubectl-proxy

2024-08-07 12:37 UTC, mimowo commented
@xmolitann would you like / find time to address the comments and complete the review?

2024-10-03 13:25 UTC, mbobrovskyi commented
/close

Due to fixed in #3160

2024-10-03 13:25 UTC, closed without merging