WIP: Update the queue name in workload only when the job is standalone
kubernetes-sigs/kueue pull request #713
Opened 2023-04-22 22:21 UTC by tenzen-y

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #697 

#### Special notes for your reviewer:

2023-04-24 07:00 UTC, ArangoGutierrez requested changes
a small nit, otherwise lgtm

2023-04-24 07:07 UTC, tenzen-y commented on CHANGELOG/CHANGELOG-0.4.md
> +- Fix sometimes updating a queue name in workloads with an empty value when using framework jobs that use batch/job internally, such as MPIJob. #713
We used to use a `Fix` without `:`.

https://github.com/kubernetes-sigs/kueue/tree/main/CHANGELOG

@ArangoGutierrez So I would like to change to the below. wdyt?

```
Fix a bug that updates a queue name in workloads with an empty value when using framework jobs that use batch/job internally, such as MPIJob. #713 
```

2023-04-24 07:23 UTC, tenzen-y commented on CHANGELOG/CHANGELOG-0.4.md
> +- Fix sometimes updating a queue name in workloads with an empty value when using framework jobs that use batch/job internally, such as MPIJob. #713
> but the "sometimes updating" is not well

I agree. Thanks for your suggestion!

2023-04-24 07:27 UTC, tenzen-y commented on CHANGELOG/CHANGELOG-0.4.md
> +- Fix sometimes updating a queue name in workloads with an empty value when using framework jobs that use batch/job internally, such as MPIJob. #713
done.

2023-04-24 07:28 UTC, ArangoGutierrez reviewed
lgtm

2023-04-24 17:48 UTC, alculquicondor commented
/assign

2023-04-24 18:34 UTC, alculquicondor commented
/lgtm
/approve

Please cherry-pick on `release-0.3`

2023-04-24 18:38 UTC, tenzen-y commented
> /lgtm /approve
> 
> Please cherry-pick on `release-0.3`

Sure.

2023-04-24 18:47 UTC, merged

2023-04-24 18:51 UTC, tenzen-y commented
/cherrypick release-0.3

2023-04-25 14:12 UTC, alculquicondor commented
/milestone v0.4

2023-04-25 16:38 UTC, tenzen-y commented
/cherrypick release-0.3